export default [
    { id: 1, name: 'Grandview Resort', location: 'Seattle', price: 150 },
    { id: 2, name: 'Ocean Breeze Inn', location: 'San Diego', price: 120 },
    { id: 3, name: 'Mountain Peak Lodge', location: 'Denver', price: 200 },
    { id: 4, name: 'Lakeside Retreat', location: 'Chicago', price: 130 },
    { id: 5, name: 'City Lights Hotel', location: 'New York', price: 250 },
    { id: 6, name: 'Sunny Beach Resort', location: 'Miami', price: 180 },
    { id: 7, name: 'Desert Oasis Hotel', location: 'Phoenix', price: 110 },
    { id: 8, name: 'Cedar Grove Inn', location: 'Portland', price: 140 },
    { id: 9, name: 'Blue Lagoon Resort', location: 'Honolulu', price: 300 },
    { id: 10, name: 'Willow Creek Lodge', location: 'Asheville', price: 160 },
    { id: 11, name: 'Skyline Hotel', location: 'Los Angeles', price: 220 },
    { id: 12, name: 'Pine Forest Retreat', location: 'Bend', price: 170 },
    { id: 13, name: 'Harbor View Inn', location: 'Boston', price: 190 },
    { id: 14, name: 'Sunset Bay Resort', location: 'Key West', price: 210 },
    { id: 15, name: 'Riverstone Lodge', location: 'Nashville', price: 125 },
    { id: 16, name: 'Starlight Hotel', location: 'Las Vegas', price: 230 },
    { id: 17, name: 'Hilltop Suites', location: 'San Francisco', price: 260 },
    { id: 18, name: 'Coral Reef Inn', location: 'Tampa', price: 140 },
    { id: 19, name: 'Evergreen Resort', location: 'Spokane', price: 155 },
    { id: 20, name: 'Maple Leaf Hotel', location: 'Toronto', price: 195 },
];
